# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memoryScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('totalTime', models.FloatField()),
                ('time1', models.FloatField()),
                ('time2', models.FloatField()),
                ('time3', models.FloatField()),
                ('time4', models.FloatField()),
                ('time5', models.FloatField()),
                ('time6', models.FloatField()),
                ('time7', models.FloatField()),
                ('time8', models.FloatField()),
                ('time9', models.FloatField()),
                ('turns', models.IntegerField()),
                ('score', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
