# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memoryScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 1, 13, 13, 52, 32, 535246))),
            ],
        ),
    ]
