# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PW', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryscore',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
