# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PW', '0002_auto_20170113_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryscore',
            name='score',
            field=models.FloatField(),
        ),
    ]
