# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PW', '0003_auto_20170114_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoryscore',
            old_name='score',
            new_name='time',
        ),
        migrations.AddField(
            model_name='memoryscore',
            name='turns',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
