# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PW', '0005_memoryscore_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoryscore',
            old_name='time',
            new_name='totalTime',
        ),
        migrations.AddField(
            model_name='memoryscore',
            name='time1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoryscore',
            name='time2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoryscore',
            name='time3',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoryscore',
            name='time4',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoryscore',
            name='time5',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoryscore',
            name='time6',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoryscore',
            name='time7',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoryscore',
            name='time8',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoryscore',
            name='time9',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
